# Generated by generate_artifactory_imports.sh
# Tue 30 Jun 2026 17:27:50 AEST


# ── Repositories (jfrog/artifactory) ─────────────────────────────────────
import {
  to = artifactory_local_docker_v2_repository.docker_trial
  id = "docker-trial"
}
import {
  to = artifactory_local_generic_repository.example_repo_local
  id = "example-repo-local"
}
import {
  to = artifactory_local_maven_repository.jk_project_mavn_dev_local
  id = "jk-project-mavn-dev-local"
}
import {
  to = artifactory_local_terraformbackend_repository.tf_trial
  id = "tf-trial"
}
import {
  to = artifactory_remote_maven_repository.jk_project_mavn_dev_remote
  id = "jk-project-mavn-dev-remote"
}
import {
  to = artifactory_virtual_maven_repository.jk_project_mavn_dev_virtual
  id = "jk-project-mavn-dev-virtual"
}

# ── Users (jfrog/artifactory) ─────────────────────────────────────────────
import {
  to = artifactory_unmanaged_user.jk_test
  id = "jk-test"
}
import {
  to = artifactory_unmanaged_user.jeffreyyk_jfrog_com
  id = "jeffreyyk@jfrog.com"
}

# ── Groups (jfrog/platform) ───────────────────────────────────────────────
import {
  to = platform_group.jk_test
  id = "jk-test"
}
import {
  to = platform_group.readers
  id = "readers"
}

# ── Permissions (jfrog/platform) ──────────────────────────────────────────
import {
  to = platform_permission.jk_test_permissiontarget
  id = "jk-test-permissiontarget"
}
import {
  to = platform_permission.Anything
  id = "Anything"
}
import {
  to = platform_permission.Any_Remote
  id = "Any Remote"
}

# ── Xray Policies (jfrog/xray) ────────────────────────────────────────────
import {
  to = xray_security_policy.Security_policy_1
  id = "Security_policy_1"
}

# ── Xray Watches (jfrog/xray) ─────────────────────────────────────────────
import {
  to = xray_watch.Security_watch_1
  id = "Security_watch_1"
}

# ── Curation Conditions (jfrog/xray) ──────────────────────────────────────

# ── Curation Policies (jfrog/xray) ────────────────────────────────────────
